# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: features.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "features.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0e\x66\x65\x61tures.proto"\x1d\n\x0e\x46\x65\x61tureRequest\x12\x0b\n\x03url\x18\x01 \x01(\t"t\n\x0f\x46\x65\x61tureResponse\x12\x30\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x1e.FeatureResponse.FeaturesEntry\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01"v\n\rLabelResponse\x12\x32\n\nprediction\x18\x01 \x03(\x0b\x32\x1e.LabelResponse.PredictionEntry\x1a\x31\n\x0fPredictionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32\xfd\x01\n\x11\x46\x65\x61turesProcessor\x12<\n\x15GenFeaturesUnusualExt\x12\x0f.FeatureRequest\x1a\x10.FeatureResponse"\x00\x12?\n\x18GenFeaturesTyposquatting\x12\x0f.FeatureRequest\x1a\x10.FeatureResponse"\x00\x12:\n\x13GenFeaturesPhishing\x12\x0f.FeatureRequest\x1a\x10.FeatureResponse"\x00\x12-\n\x08GenLabel\x12\x0f.FeatureRequest\x1a\x0e.LabelResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "features_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FEATURERESPONSE_FEATURESENTRY"]._loaded_options = None
    _globals["_FEATURERESPONSE_FEATURESENTRY"]._serialized_options = b"8\001"
    _globals["_LABELRESPONSE_PREDICTIONENTRY"]._loaded_options = None
    _globals["_LABELRESPONSE_PREDICTIONENTRY"]._serialized_options = b"8\001"
    _globals["_FEATUREREQUEST"]._serialized_start = 18
    _globals["_FEATUREREQUEST"]._serialized_end = 47
    _globals["_FEATURERESPONSE"]._serialized_start = 49
    _globals["_FEATURERESPONSE"]._serialized_end = 165
    _globals["_FEATURERESPONSE_FEATURESENTRY"]._serialized_start = 118
    _globals["_FEATURERESPONSE_FEATURESENTRY"]._serialized_end = 165
    _globals["_LABELRESPONSE"]._serialized_start = 167
    _globals["_LABELRESPONSE"]._serialized_end = 285
    _globals["_LABELRESPONSE_PREDICTIONENTRY"]._serialized_start = 236
    _globals["_LABELRESPONSE_PREDICTIONENTRY"]._serialized_end = 285
    _globals["_FEATURESPROCESSOR"]._serialized_start = 288
    _globals["_FEATURESPROCESSOR"]._serialized_end = 541
# @@protoc_insertion_point(module_scope)
