# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import features_pb2 as features__pb2

GRPC_GENERATED_VERSION = "1.66.2"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in features_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class FeaturesProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenFeaturesUnusualExt = channel.unary_unary(
            "/FeaturesProcessor/GenFeaturesUnusualExt",
            request_serializer=features__pb2.FeatureRequest.SerializeToString,
            response_deserializer=features__pb2.FeatureResponse.FromString,
            _registered_method=True,
        )
        self.GenFeaturesTyposquatting = channel.unary_unary(
            "/FeaturesProcessor/GenFeaturesTyposquatting",
            request_serializer=features__pb2.FeatureRequest.SerializeToString,
            response_deserializer=features__pb2.FeatureResponse.FromString,
            _registered_method=True,
        )
        self.GenFeaturesPhishing = channel.unary_unary(
            "/FeaturesProcessor/GenFeaturesPhishing",
            request_serializer=features__pb2.FeatureRequest.SerializeToString,
            response_deserializer=features__pb2.FeatureResponse.FromString,
            _registered_method=True,
        )
        self.GenLabel = channel.unary_unary(
            "/FeaturesProcessor/GenLabel",
            request_serializer=features__pb2.FeatureRequest.SerializeToString,
            response_deserializer=features__pb2.LabelResponse.FromString,
            _registered_method=True,
        )


class FeaturesProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenFeaturesUnusualExt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenFeaturesTyposquatting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenFeaturesPhishing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenLabel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FeaturesProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GenFeaturesUnusualExt": grpc.unary_unary_rpc_method_handler(
            servicer.GenFeaturesUnusualExt,
            request_deserializer=features__pb2.FeatureRequest.FromString,
            response_serializer=features__pb2.FeatureResponse.SerializeToString,
        ),
        "GenFeaturesTyposquatting": grpc.unary_unary_rpc_method_handler(
            servicer.GenFeaturesTyposquatting,
            request_deserializer=features__pb2.FeatureRequest.FromString,
            response_serializer=features__pb2.FeatureResponse.SerializeToString,
        ),
        "GenFeaturesPhishing": grpc.unary_unary_rpc_method_handler(
            servicer.GenFeaturesPhishing,
            request_deserializer=features__pb2.FeatureRequest.FromString,
            response_serializer=features__pb2.FeatureResponse.SerializeToString,
        ),
        "GenLabel": grpc.unary_unary_rpc_method_handler(
            servicer.GenLabel,
            request_deserializer=features__pb2.FeatureRequest.FromString,
            response_serializer=features__pb2.LabelResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "FeaturesProcessor", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("FeaturesProcessor", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class FeaturesProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenFeaturesUnusualExt(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/FeaturesProcessor/GenFeaturesUnusualExt",
            features__pb2.FeatureRequest.SerializeToString,
            features__pb2.FeatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GenFeaturesTyposquatting(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/FeaturesProcessor/GenFeaturesTyposquatting",
            features__pb2.FeatureRequest.SerializeToString,
            features__pb2.FeatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GenFeaturesPhishing(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/FeaturesProcessor/GenFeaturesPhishing",
            features__pb2.FeatureRequest.SerializeToString,
            features__pb2.FeatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GenLabel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/FeaturesProcessor/GenLabel",
            features__pb2.FeatureRequest.SerializeToString,
            features__pb2.LabelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
